[workspace]
members = ["day-*", "common"]
resolver = "2"

[workspace.dependencies]
common = { path = "./common" }
itertools = "0.13.0"
regex = "1.11.1"
glam = "0.29.2"
rstest = {version = "0.23.0", default-features = false, features = ["crate-name"]}
