[package]
name = "day-14"
version = "0.1.0"
edition = "2021"

[dependencies]
common = {workspace = true}
regex = {workspace = true}
itertools = {workspace = true}
plotters = "0.3.7"
indicatif = "0.17.9"
