[package]
name = "day-06"
version = "0.1.0"
edition = "2021"

[dependencies]
glam.workspace = true
indicatif = "0.17.9"
itertools.workspace = true
pathfinding = "4.12.0"
rayon = "1.10.0"
rstest.workspace = true
